version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db_mol
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: nestjs-app
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
    command: sh -c "npx prisma migrate dev && pnpm run start:dev"

volumes:
  mysql-data: